### ISSUE TITLE
Adding character device crashes the application (first-time setup) or reboots the system 

### ISSUE THREAD

**Issue by Robert9157** [Arian04/android-hid-client#22]
**Describe the bug**
The addition of the character device either crashes the application (during first setup and superuser request), or causes a system reboot.

**To Reproduce**
Enable the character device

**Expected behavior**

**Screenshots**

**Device details (please complete the following information):**
 - Device: [e.g. Google Pixel 5] Realme 8
 - OS: [e.g. Android 12, LineageOS 19] Android 13, Custom ROM AfterLife 6.0
 - Soft Keyboard: [e.g. Hacker's Keyboard] Gboard
 - Are You Rooted? [Yes/No] Yes
 - Root Method: [e.g. Magisk] Magisk

**Additional context**

**Comment by Arian04** [comment]
I've heard reports of variations of this happening to lots of people. especially in the issues of tejado's USB Gadget Tool app. my device specifically (since updating to android 14/LineageOS 21) hard reboots if I try and remove any functions from any USB gadgets through tejado's app or even a root shell. it leads me to believe it's multiple variations of the same (or a similar) kernel bug.

**Comment by Arian04** [comment]
wait a minute. I just got a chance to re-read this while not on a phone. An application crash is strange. Once I get a chance I'm gonna make a little test application to see exactly what part of the messing-with-gadgets stuff causes the reboot and/or application crash.

I'm thinking that I made some assumption about gadgets that isn't necessarily true for all device manufacturers and/or ROMs

**Comment by Arian04** [comment]
So after the simplification, my app only uses root in these places
- Adding HID functions to the default Android USB gadget (I think I only need `system` permissions for this though)
- Fixing `/dev/hidg0`/`/dev/hidg1` file mode permissions and adding SELinux policy exception (I don't think I can do this without root, BUT maybe I can find a way for it to not be necessary)
- Grabbing debug logs (unnecessary, wasn't considering non-root users when I wrote it)

So basically, I might be able to get it working if I can get `system` permissions. I'll try to look into this further sometime soon.

**Comment by Arian04** [comment]
OOPS, last comment was meant for #17

**Comment by Arian04** [comment]
try the APK from the new v2.1.0 release. If that doesn't work, fully uninstall the app, then reboot your phone, download [this apk](https://files.arianb.me/app-v2.1.0-debug.apk) for testing purposes (I would've attached it here instead of using an external link but Github complained about it being an APK), install it, then try it.

**Comment by Arian04** [comment]
thanks for the extremely helpful reports!! glad to hear the device reboot doesn't happen anymore. 

As far as the application crash, I'm pretty sure it's because I forgot to add a second waitFor in case the shell command needs to be forcibly destroyed. The Android Process docs said that and I remember planning to add it but during a big refactor it slipped my mind. Not sure you cared for the full explanation but I'm also leaving the notes for my later reference lol.

Now the character devices not being created is weirder. I'm thinking of a few possibilities, first of which is that your kernel might not have HID gadget functions enabled, but rather than dumping all my random troubleshooting ideas into here, I'm gonna spend some time to think up what information I want and maybe come up with a concise command you can run to get all that info at once. I'm also going to look through tejado's USB gadget tool app's issues again to see if any other devices exhibit this issue (since before I was looking for issues relating to reboots only) so I can get to the root cause without requiring as much back-and-forth.

but if you want to quickly check if your kernel has support, you can provide the output of this command I stole from the above-mentioned app's issues: `echo KERNEL_VERSION=\`(uname -r |cut -d '-' -f1 )\` && (gunzip -c /proc/config.gz | grep -i configfs | sed 's/# //; s/ is not set/=NOT_SET/')`

**Comment by Arian04** [comment]
haven't made as many improvements to debugging as I planned to since I've been pretty busy but can you uninstall the app (if you still have it installed), install the latest one from the Github releases page, try it, and if it's still broken, export logs from the bottom of the settings page and attach them here.

**Comment by Arian04** [comment]
thank you for the quick response!

ugh it seems like my log-writing code that I tested on two physical devices with different android versions somehow didn't work!! If it's not too much trouble, could you please run `logcat -e me.arianb.usb_hid_client -t 1000` after launching the app with debugging enabled? thanks so much!

**Comment by Arian04** [comment]
thank you! and this log was taken after enabling the "debug mode" switch in the app's settings menu? Because I just re-read my previous message and realized that I didn't mention that super clearly.

**Comment by Arian04** [comment]
then I have much more testing to do because nothing in the logs seems useful. I'll ping again once I make progress.

**Comment by Arian04** [comment]
I finally got around to improving the ability to troubleshoot issues like this in the latest release (v2.3.0). Do you mind trying that out and exporting a log file for me to check out?

You would just have to:
1. Install v2.3.0
2. Give the app root permissions
3. Go to the "Troubleshooting" screen in the overflow menu in the top right
4. Click the button at the bottom to export logs (a screenshot of the troubleshooting page would also be nice)

**Comment by JinsimeuroGamsadeurimnida** [comment]
Nintendo Switch, LineageOS 18.1, just reposting a log from someone who tried it. RIP Switch:

Do we have root permissions?: true
Root method: MAGISK

------------------------------
character device info for: /dev/hidg0
does it exist?: false
is it visible without root?: false
permissions: 
null

character device info for: /dev/hidg1
does it exist?: false
is it visible without root?: false
permissions: 
null

------------------------------
version: 4.9.141-g0bef9c0cd8bb-dirty
has ConfigFS support?: true
has ConfigFS HID function support?: false
-
relevant snippet of kernel config: 
CONFIG_USB_CONFIGFS=y
# CONFIG_USB_CONFIGFS_SERIAL is not set
CONFIG_USB_CONFIGFS_ACM=y
# CONFIG_USB_CONFIGFS_OBEX is not set
CONFIG_USB_CONFIGFS_NCM=y
CONFIG_USB_CONFIGFS_ECM=y
# CONFIG_USB_CONFIGFS_ECM_SUBSET is not set
CONFIG_USB_CONFIGFS_RNDIS=y
# CONFIG_USB_CONFIGFS_EEM is not set
CONFIG_USB_CONFIGFS_MASS_STORAGE=y
CONFIG_USB_CONFIGFS_F_LB_SS=y
CONFIG_USB_CONFIGFS_F_FS=y
CONFIG_USB_CONFIGFS_F_MTP=y
CONFIG_USB_CONFIGFS_F_PTP=y
CONFIG_USB_CONFIGFS_F_ACC=y
CONFIG_USB_CONFIGFS_F_AUDIO_SRC=y
CONFIG_USB_CONFIGFS_UEVENT=y
# CONFIG_USB_CONFIGFS_F_UAC1 is not set
# CONFIG_USB_CONFIGFS_F_UAC2 is not set
CONFIG_USB_CONFIGFS_F_MIDI=y
# CONFIG_USB_CONFIGFS_F_HID is not set
# CONFIG_USB_CONFIGFS_F_UVC is not set
# CONFIG_USB_CONFIGFS_F_PRINTER is not set
# CONFIG_IIO_CONFIGFS is not set
CONFIG_CONFIGFS_FS=y

------------------------------
Logs: 
unknown_tagINFODetected root method as: MAGISK
unknown_tagINFODetected root method as: MAGISK

**Comment by Arian04** [comment]
yea it looks like that kernel is missing HID function support. the version says it's dirty so I'm assuming that person built a custom kernel. in that case, it should be very simple to just enable HID function support and rebuild it.

**Comment by Arian04** [comment]
closing due to lack of response by the author of the issue. will reopen if there's a response later on.
